# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ChatPedia' do
  pod 'Firebase'
  pod 'FirebaseUI/Core', '~> 0.3'
  pod 'JSQMessagesViewController'

end

target 'ChatPediaTests' do

end
